django_gramm/django_gramm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from . import views

app_name = "django_gramm"

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", views.home_page, name="home"),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("auth/", include("social_django.urls", namespace="social")),
]

django_gramm/posts/urls.py
from django.urls import path

from .views import LikePostApiView, PostCreateView, PostsListView

app_name = "posts"

urlpatterns = [
    path("", PostsListView.as_view(), name="list"),
    path("new-post/", PostCreateView.as_view(), name="new-post"),
    path("post-api/<int:post_id>", LikePostApiView.as_view(), name="like-post-api"),
]

django_gramm/users/urls.py
from django.urls import path

from .forms import LoginForm
from .views import (
    ConfigurateView,
    CustomLoginView,
    FollowUnfollowView,
    LogoutView,
    ProfileView,
    RegisterView,
)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        CustomLoginView.as_view(
            redirect_authenticated_user=True,
            next_page="/users/profile/<str:username>/",
            template_name="users/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("configurate/", ConfigurateView.as_view(), name="configurate"),
    path("profile/<str:username>/", ProfileView.as_view(), name="profile"),
    path(
        "follow_unfollow/<str:username>/",
        FollowUnfollowView.as_view(),
        name="follow_unfollow",
    ),
]

django_gramm/users/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    avatar = CloudinaryField(
        "avatar",
        default="https://res.cloudinary.com/dn1lqn2zp/image/upload/v1724937965/default_c0yccz.jpg",
    )
    bio = models.TextField()

    def __str__(self):
        return self.user.username

    def number_of_followers(self):
        return Subscription.objects.filter(following=self.user).count()

    def number_of_following(self):
        return Subscription.objects.filter(follower=self.user).count()


class Subscription(models.Model):
    follower = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        User, related_name="followers", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("follower", "following")

    def __str__(self):
        return f"{self.follower.username} follows {self.following.username}"

django_gramm/users/forms.py
from cloudinary.forms import CloudinaryFileField
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control",
            }
        ),
    )
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control",
            }
        ),
    )
    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
            }
        ),
    )
    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class ProfileConfigurate(forms.ModelForm):
    avatar = CloudinaryFileField()

    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "avatar", "bio"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["avatar"].options = {
            "tags": "avatar",
            "format": "png",
            "crop": "pad",
            "width": 600,
            "height": 400,
            "quality": "auto",
        }


class LoginForm(AuthenticationForm):

    username = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control",
                "data-toggle": "password",
                "id": "password",
                "name": "password",
            }
        ),
    )

    class Meta:
        model = User
        fields = ["username", "password"]

django_gramm/users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, UpdateView

from .forms import LoginForm, ProfileConfigurate, RegisterForm
from .models import Profile, Subscription


class RegisterView(View):
    form_class = RegisterForm
    initial = {"key": "value"}
    template_name = "users/register.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data.get("email")
            messages.success(request, f"Account created for {email}")
            login(request, user)
            return redirect("users:configurate")
        return render(request, self.template_name, {"form": form})


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = "users/login.html"

    def get_success_url(self):
        return self.get_redirect_url() or reverse_lazy(
            "users:profile", kwargs={"username": self.request.user.username}
        )


class LogoutView(View):

    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect("/")


class ConfigurateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileConfigurate
    success_message = "Your profile is updated successfully"
    template_name = "users/configurate_page.html"
    login_url = "/users/login/"

    def get_object(self):
        return self.request.user.profile

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response

    def get_success_url(self):
        return reverse_lazy(
            "users:profile", kwargs={"username": self.request.user.username}
        )


class ProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "users/profile.html"
    context_object_name = "profile"
    login_url = "/users/login/"

    def get_object(self):
        username = self.kwargs.get("username")
        user = get_object_or_404(User, username=username)
        return get_object_or_404(Profile, user=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_user = self.get_object().user
        context["is_following"] = self.request.user.following.filter(
            following=profile_user
        ).exists()
        return context


class FollowUnfollowView(View):
    def post(self, request, username, *args, **kwargs):
        following = get_object_or_404(User, username=username)
        if request.user != following:
            subscription, created = Subscription.objects.get_or_create(
                follower=request.user, following=following
            )
            if created:
                Following = True
            else:
                subscription.delete()
                Following = False
            return JsonResponse(
                {
                    "subscription": Following,
                    "followers": Subscription.objects.filter(
                        following=following
                    ).count(),
                    "following": Subscription.objects.filter(
                        follower=following
                    ).count(),
                }
            )
        return JsonResponse(
            {"error": "You cannot follow/unfollow yourself"}, status=400
        )

django_gramm/users/templates/users/configurate_page.html
{% extends 'layout.html' %}

{% block title %}
    Configurate
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
      <button class="form-submit btn btn-success">Submit</button>
    </form>
{% endblock %}

django_gramm/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
    <div class="container mt-5">
    <h1>User Login</h1>
    <form class="form-with-validation" action="/users/login/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit btn btn-success">LOGIN</button>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
    <div class="d-flex flex-column align-items-start">
<a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger btn-lg d-flex align-items-center">
    <i class="bi bi-google me-2"></i> Увійти через Google
</a>

        <a href="{% url 'social:begin' 'github' %}" class="btn btn-dark btn-lg d-flex align-items-center">
        <i class="bi bi-github me-2"></i> Увійти через GitHub
    </a>
    </div>
    </div>
{% endblock %}

django_gramm/users/templates/users/profile.html
{% extends 'layout.html' %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    {% load cloudinary %}
    {% cloudinary profile.avatar quality='auto' width=600 height=400 crop='pad' %}
    <h1>{{ profile.first_name }}</h1>
    <h1>{{ profile.last_name }}</h1>
    <h1>{{ profile.bio }}</h1>
{% if user.is_authenticated %}
    {% if profile.user != request.user %}
            <form action="{% url 'users:follow_unfollow' profile.user.username %}" method="post" class="follow_unfollow">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary follow">
                {% if is_following %}
                Unfollow
                {% else %}
                Follow
                {% endif %}
                </button>
            </form>
    {% endif %}
{% endif %}
<h1 class="followers-count">Followers: {{ profile.number_of_followers }}</h1>
<h1 class="following-count">Following: {{ profile.number_of_following }}</h1>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    $('.follow_unfollow').on('submit', function(e) {
        e.preventDefault();
        var form = $(this);
        var url = form.attr('action');
        var csrftoken = form.find('input[name="csrfmiddlewaretoken"]').val();

        $.ajax({
            url: url,
            type: 'POST',
            headers: {'X-CSRFToken': csrftoken},
            dataType: 'json',
            success: function(response) {
                if (response.subscription) {
                    form.find('button').text('Unfollow');
                } else {
                    form.find('button').text('Follow');
                }
                form.parent().find('.followers-count').text('Followers: ' + response.followers);
                form.parent().find('.following-count').text('Following: ' + response.following);
            },
            error: function(response) {
                alert('Something wrong ');
            }
        });
    });
});

</script>
{% endblock scripts %}
{% endblock content %}

django_gramm/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit btn btn-primary">REGISTER</button>
    </form>
{% endblock %}