django_gramm/django_gramm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from . import views

app_name = "django_gramm"

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", views.home_page, name="home"),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("auth/", include("social_django.urls", namespace="social")),
]

django_gramm/posts/urls.py
from django.urls import path

from .views import LikePostApiView, PostCreateView, PostsListView

app_name = "posts"

urlpatterns = [
    path("", PostsListView.as_view(), name="list"),
    path("new-post/", PostCreateView.as_view(), name="new-post"),
    path("post-api/<int:post_id>", LikePostApiView.as_view(), name="like-post-api"),
]

django_gramm/users/urls.py
from django.urls import path

from .forms import LoginForm
from .views import (
    ConfigurateView,
    CustomLoginView,
    FollowUnfollowView,
    LogoutView,
    ProfileView,
    RegisterView,
)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        CustomLoginView.as_view(
            redirect_authenticated_user=True,
            next_page="/users/profile/<str:username>/",
            template_name="users/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("configurate/", ConfigurateView.as_view(), name="configurate"),
    path("profile/<str:username>/", ProfileView.as_view(), name="profile"),
    path(
        "follow_unfollow/<str:username>/",
        FollowUnfollowView.as_view(),
        name="follow_unfollow",
    ),
]

django_gramm/posts/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=75)
    images = CloudinaryField("images")
    tags = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.tags = " ".join(
            [tag if tag.startswith("#") else "#" + tag for tag in self.tags.split()]
        )
        super(Post, self).save(*args, **kwargs)


class Reaction(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE, related_name="reaction")
    likes = models.ManyToManyField(User, related_name="post_likes", blank=True)
    unlikes = models.ManyToManyField(User, related_name="post_unlikes", blank=True)

    def number_of_likes(self):
        return self.likes.count()

    def number_of_unlikes(self):
        return self.unlikes.count()

django_gramm/posts/forms.py
from cloudinary.forms import CloudinaryFileField
from django import forms

from . import models


class CreatePost(forms.ModelForm):
    images = CloudinaryFileField()

    class Meta:
        model = models.Post
        fields = ["title", "images", "tags"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["images"].options = {
            "tags": "new_image",
            "format": "png",
            "crop": "pad",
            "width": 600,
            "height": 400,
            "quality": "auto",
        }

django_gramm/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from .forms import CreatePost
from .models import Post, Reaction


class PostsListView(ListView):
    model = Post
    template_name = "posts/posts_list.html"
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by("-date")


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CreatePost
    template_name = "posts/post_new.html"
    login_url = "/users/login/"
    success_url = reverse_lazy("posts:list")

    def form_valid(self, form):
        newpost = form.save(commit=False)
        newpost.author = self.request.user
        newpost.save()
        return super().form_valid(form)


class LikePostApiView(View):
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        reaction, created = Reaction.objects.get_or_create(post=post)
        liked = False
        if request.user in reaction.likes.all():
            reaction.likes.remove(request.user)
        else:
            liked = True
            reaction.likes.add(request.user)
        data = {"liked": liked, "updated_likes_count": reaction.likes.count()}
        return JsonResponse(data)

django_gramm/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
   New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form.as_p}}
            <input type="submit" value="Upload">
        </form>
    </section>
{% endblock %}

django_gramm/posts/templates/posts/posts_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'layout.html' %}
{% load cloudinary %}
{% block title %}
    Posts
{% endblock title %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<section>
    {% for post in posts %}
    <article class="post">

        {% cloudinary post.images quality='auto' width=600 height=400 crop='pad' %}
        <h1>{{ post.title }}</h1>
        <h2>{{ post.tags }}</h2>
        <h1>{{ post.date }} by <a href="{% url 'users:profile' username=post.author.username %}">
                {{post.author }}
            </a>
        </h1>
        {% if user.is_authenticated %}
            <form action="{% url 'posts:like-post-api' post.id %}" method="POST" class="like-form">
    {% csrf_token %}
    <button class="btn  like-button" type="submit">
        {% if user in post.reaction.likes.all %}
            <i class="fas fa-heart"></i>
        {% else %}
             <i class="far fa-heart"></i>
        {% endif %}
    </button>
</form>
            <p>Likes: {{ post.reaction.number_of_likes }}</p>
        {% endif %}
    </article>
     {% endfor %}
</section>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    $('.like-form').on('submit', function(e) {
        e.preventDefault();
        var form = $(this);
        var url = form.attr('action');
        var csrftoken = form.find('input[name="csrfmiddlewaretoken"]').val();

        $.ajax({
            url: url,
            type: 'POST',
            headers: {'X-CSRFToken': csrftoken},
            dataType: 'json',
            success: function(response) {
                console.log(response);
                if (response.liked) {
                    form.find('.like-button i').removeClass('far fa-heart').addClass('fas fa-heart');
                } else {
                    form.find('.like-button i').removeClass('fas fa-heart').addClass('far fa-heart');
                }
                form.siblings('p').text('Likes: ' + response.updated_likes_count);
            },
            error: function(response) {
                alert('Something wrong ');
            }
        });
    });
});

</script>
{% endblock scripts %}
{% endblock content %}
</html>