django_gramm/django_gramm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from . import views

app_name = "django_gramm"

urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("admin/", admin.site.urls),
    path("", views.home_page, name="home"),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("auth/", include("social_django.urls", namespace="social")),
]

django_gramm/posts/urls.py
from django.urls import path

from .views import LikePostApiView, PostCreateView, PostsListView

app_name = "posts"

urlpatterns = [
    path("", PostsListView.as_view(), name="list"),
    path("new-post/", PostCreateView.as_view(), name="new-post"),
    path("post-api/<int:post_id>", LikePostApiView.as_view(), name="like-post-api"),
]

django_gramm/users/urls.py
from django.urls import path

from .forms import LoginForm
from .views import (
    ConfigurateView,
    CustomLoginView,
    FollowUnfollowView,
    LogoutView,
    ProfileView,
    RegisterView,
)

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "login/",
        CustomLoginView.as_view(
            redirect_authenticated_user=True,
            next_page="/users/profile/<str:username>/",
            template_name="users/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("configurate/", ConfigurateView.as_view(), name="configurate"),
    path("profile/<str:username>/", ProfileView.as_view(), name="profile"),
    path(
        "follow_unfollow/<str:username>/",
        FollowUnfollowView.as_view(),
        name="follow_unfollow",
    ),
]

django_gramm/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Django_Gramm
{% endblock %}

{% block content %}
    <h1>DjangoGramm</h1>
        <p>It is a popular social network and mobile application for sharing photos and videos,
 which allows users to create, edit
 and share multimedia content with friends and followers.
 Launched in 2024, DjangoGramm is quickly becoming one of the most popular applications,
 especially among young audiences, and is now a key platform for visual content,
 personal branding, marketing and social interaction.
        </p>
{% endblock %}

django_gramm/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<link rel='icon' href='https://res.cloudinary.com/dn1lqn2zp/image/upload/v1728490538/favicon_yvsbyc.ico' type='image/x-icon'/>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'bundles/styles.css' %}">
</head>
<body>
    <nav class="navbar" style="background-color: #9e1c9e;">
  <div class="container-fluid">
      <a href="/" class="text-white">🏠</a> |
      <a href="/posts/" class="text-white">📰</a> |
      <a href="/posts/new-post/" class="text-white">NEW POST</a> |
      {% if user.is_authenticated %}
      <a href="{% url 'users:profile' request.user.username %}" class="text-white">MY PROFILE</a> |
      <a href="/users/configurate/" class="text-white">CONFIGURATE</a> |
        <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button btn btn-danger" aria-label="User Logout" title="User Logout">LOGOUT</button>
            </form>

      {% else %}
            <a href="/users/login/" class="text-white">LOGIN</a> |
            <a href="/users/register/" class="text-white">REGISTRATION</a>
      {% endif %}
  </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
<script src="{% static 'bundles/bundle.js' %}"></script>
</body>
</html>